FullStack/Dream_Housing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FullStack/app/urls.py
from django.urls import path
from app.views import *

app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('login_view/', login_view, name='login_view'),
    path('log_out_view/', log_out_view, name='log_out_view'),
    path('registration/', registration, name='registration'),
    path('profile/<str:pk>', profile, name='profile'),
    path('delete_profile/<str:pk>', delete_profile, name='delete_profile'),
    path('notification', notification, name='notification'),
    
    path('listing/', listing, name='listing'),
    path('rent_listing/', rent_listing, name='rent_listing'),
    path('sale_listing/', sale_listing, name='sale_listing'),
    path('search_result/', search_result, name='search_result'),
    
    path('apartment/<int:pk>', apartment, name='apartment'),
    path('add_apartment/', add_apartment, name='add_apartment'),
    path('edit_apartment/<int:pk>', edit_apartment, name='edit_apartment'),
    path('delete_apartment/', delete_apartment, name='delete_apartment'),
    path('agents/', agents, name='agents'),
    
    path('pay_a_visit/', pay_a_visit, name='pay_a_visit'),
    path('booking/', booking, name='booking'),

]

FullStack/app/templates/app/agents.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid m-0 page_header p-5" style="background-image: url('{% static 'imgs/header_background.png' %}')">
    <p class="m-0">
        <a href="{% url 'app:index' %}" class="text-orange hover-white">Home</a>
        >
        <a href="#" class="text-white hover-white">Agent</a>
    </p>
    <h3>Our Agents</h3>
</div>

<div class="row mx-0 my-5">
    {% for i in agents %}
        <!-- Start: Agent Card -->
        <div class="agent_card my-3 mx-auto">
            <img src="{{ i.img.url }}" class="img-fluid d-flex mx-auto">
            <h6 class="text-center mt-2 p-0 fw-600">{{ i.fullname }}</h6>
            <p class="text-center mb-2 p-0">Renowned Agent</p>
            <div class="row m-0 d-flex justify-content-center">
                <a href="{% url 'app:profile' pk=i.username %}" class="btn btn-xl btn-orange px-4">View Profile</a>
            </div>
        </div>
        <!-- End: Agent Card -->
    {% endfor %}
</div>



<div style="height: 60px;"></div>


{% endblock %}

FullStack/app/templates/app/apartment.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="bg-lightgrey">
    <div class="row m-0 py-5 px-2 d-flex justify-content-center">
        <div class="col-xl-4 col-md-6 mx-2 profile_pic" style="background-image: url('{{ this_apartment.img.url }}')">
            <div class="profile_tag">
                <div class="row m-0">
                    <img src="{% static 'icons/profile_active_ico.png' %}" class="mt-1 mr-3">
                    For {{ this_apartment.type }}
                </div>                
            </div>
        </div>
        <div class="col-xl-5 mx-2 profile_description font_Commissioner">
            <h3 class="fw-800">{{ this_apartment.name }}</h3>
            <div class="row m-0 p-0 fw-400 text-black">
                <img src="{% static 'icons/location_black.png' %}" class="mr-2 mt-1" style="height: 20px;">
                <p class="mt-1 fs-15">{{ this_apartment.location }}</p>
                {% if own_apartment %}
                <a href="#" class="ml-auto hover_scale-9" data-toggle="modal" data-target="#deleteconformationmodal">
                    <img src="{% static 'icons/trash.png' %}" class="mr-2" style="height: 20px;">
                </a>
                <a href="{% url 'app:edit_apartment' pk=this_apartment.pk %}" class="ml-2 hover_scale-9" style="margin-top: 2px;">
                    <i class="fa fa-pencil text-grey fs-22"></i>
                </a>
                {% endif %}
            </div>
            <div class="profile_points my-4 py-3">
                <div class="row m-0 pt-2">
                    <p class="fw-800 font_Josefin text-upper">Apartment ID:</p>
                    <p class="fw-400 ml-auto fs-14">{{ this_apartment.pk }}</p>
                </div>
                <div class="row m-0">
                    <p class="fw-800 font_Josefin text-upper">Building year:</p>
                    <p class="fw-400 ml-auto fs-14">{{ this_apartment.building_year }}</p>
                </div>
                <div class="row m-0">
                    <p class="fw-800 font_Josefin text-upper">Area:</p>
                    <p class="fw-400 ml-auto fs-14">{{ this_apartment.area }} sq ft</p>
                </div>
                <div class="row m-0">
                    <p class="fw-800 font_Josefin text-upper">Cost:</p>
                    <p class="fw-600 ml-auto fs-14 text-dark">{{ this_apartment.price }} /month</p>
                </div>
                <div class="row m-0">
                    <p class="fw-800 font_Josefin text-upper">Agent:</p>
                    {% if agent %}
                        <a href="{% url 'app:profile' pk=agent.pk %}" class="fw-400 ml-auto fs-14 text-orange">{{ agent.fullname }}</a>
                    {% endif %}
                </div>
            </div>
            {% if not own_apartment %}
                {% if not this_apartment.is_booked %}
                    <div class="row m-0">
                        <a href="#" class="btn btn-md btn-outline-dark mx-2 my-2 px-45 hover_scale-9" data-toggle="modal" data-target="#pay_a_visit">Pay a Visit</a>
                        <a href="#" class="btn btn-md btn-orange mx-2 my-2 px-4 hover_scale-9" data-toggle="modal" data-target="#booking_successful">Make a Booking</a>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>

    <div class="container-fluid my-5">
        <div class="row m-0 prx-4 d-flex justify-content-center">
            <div class="col-xl-10 prx-45">
                <h4 class="fw-800 my-3">About {{ this_apartment.name }}</h4>
                <p class="profile_about">
                    {{ this_apartment.about }}
                </p>
            </div>
        </div>
    </div>


    <div class="container-fluid my-5">
        <div class="row m-0 prx-4 d-flex justify-content-center">
            <div class="col-xl-10 room_info prx-45 py-4">
                <div class="row m-0">
                    <div class="col-xl-3 col-sm-6 mx-auto">
                        <h2 class="fw-700">{{ this_apartment.bedroom }}</h2>
                        <p class="text-upper fw-600 fs-13" style="letter-spacing: 1px;">Numbers of Bedrooms</p>
                    </div>
                    <div class="col-xl-3 col-sm-6 mx-auto">
                        <h2 class="fw-700">{{ this_apartment.living }}</h2>
                        <p class="text-upper fw-600 fs-13" style="letter-spacing: 1px;">Numbers of Living Room</p>
                    </div>
                    <div class="col-xl-3 col-sm-6 mx-auto">
                        <h2 class="fw-700">{{ this_apartment.dinning }}</h2>
                        <p class="text-upper fw-600 fs-13" style="letter-spacing: 1px;">Numbers of Dinning</p>
                    </div>
                    <div class="col-xl-3 col-sm-6 mx-auto">
                        <h2 class="fw-700">{{ this_apartment.bathroom }}</h2>
                        <p class="text-upper fw-600 fs-13" style="letter-spacing: 1px;">Numbers of Bathroom</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="container-fluid my-5">
        <div class="row m-0 prx-4 d-flex justify-content-center">
            <div class="col-xl-10 prx-45">
                <h4 class="fw-800 my-3">Facilities</h4>
                <div class="row m-0 py-4">
                    {% if this_apartment.garage %}
                        <div class="col-xl-4 col-sm-6 mx-auto my-4">
                            <img src="{% static 'icons/garage.png' %}" class="facility_ico">
                            <p class="text-upper fw-700 fs-14 my-2" style="letter-spacing: 1px;">Garage Avaiavle</p>
                        </div>
                    {% endif %}
                    {% if this_apartment.watchman %}
                        <div class="col-xl-4 col-sm-6 mx-auto my-4">
                            <img src="{% static 'icons/guard.png' %}" class="facility_ico">
                            <p class="text-upper fw-700 fs-14 my-2" style="letter-spacing: 1px;">Fulltime Watchman</p>
                        </div>
                    {% endif %}
                    {% if this_apartment.garden %}
                        <div class="col-xl-4 col-sm-6 mx-auto my-4">
                            <img src="{% static 'icons/gardening.png' %}" class="facility_ico">
                            <p class="text-upper fw-700 fs-14 my-2" style="letter-spacing: 1px;">Attatched Garden</p>
                        </div>
                    {% endif %}
                    {% if this_apartment.swimmingpool %}
                        <div class="col-xl-4 col-sm-6 mx-auto my-4">
                            <img src="{% static 'icons/swimming-pool.png' %}" class="facility_ico">
                            <p class="text-upper fw-700 fs-14 my-2" style="letter-spacing: 1px;">Attatched swimming-pool</p>
                        </div>
                    {% endif %}
                    {% if this_apartment.hospital %}
                        <div class="col-xl-4 col-sm-6 mx-auto my-4">
                            <img src="{% static 'icons/hospital.png' %}" class="facility_ico">
                            <p class="text-upper fw-700 fs-14 my-2" style="letter-spacing: 1px;">Nearby Hospital</p>
                        </div>
                    {% endif %}
                    {% if this_apartment.shoppingmall %}
                        <div class="col-xl-4 col-sm-6 mx-auto my-4">
                            <img src="{% static 'icons/shopping-mall.png' %}" class="facility_ico">
                            <p class="text-upper fw-700 fs-14 my-2" style="letter-spacing: 1px;">Nearby Shopping Mall</p>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div style="height: 120px;"></div>

</div>



  
<!-- Start: Pay A Visit Modal -->
<div class="modal fade" id="pay_a_visit" tabindex="-1" role="dialog" aria-labelledby="pay_a_visitLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="booking_successfulLabel">Schedule A Date For Visit</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'app:pay_a_visit' %}" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="form-group mb-2">
                        <label class="sr-only" name="tour_date">Pick a date</label>
                        <input type="date" class="form-control" name="visit_date" required>
                    </div>
                    <input type="hidden" value="{{ this_apartment.pk }}" name="apartment_id" >                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Confirm</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End: Pay A Visit Modal -->


<!-- Start: Booking Successfull Modal -->
<div class="modal fade" id="booking_successful" tabindex="-1" role="dialog" aria-labelledby="booking_successfulLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="pay_a_visitLabel">Booking Conformation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'app:booking' %}" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    <p>Are you sure to proceed with the booking process for this apartment?</p>
                    <input type="hidden" value="{{ this_apartment.pk }}" name="apartment_id" >                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Confirm</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End: Pay A Visit Modal -->


{% if own_apartment %}
<!-- Start: Delet Confirm Modal -->
<div class="modal fade" id="deleteconformationmodal" tabindex="-1" role="dialog" aria-labelledby="deleteconformationmodalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteconformationmodalLabel">Delete Profile</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'app:delete_apartment' %}" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    Are you sure about delete this apartment from listing?
                    <input type="hidden" name="apartment_pk" value="{{ this_apartment.pk }}">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Process Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End: Delet Confirm Modal -->
{% endif %}


{% endblock %}

FullStack/app/templates/app/listing.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid m-0 page_header p-5" style="background-image: url('{% static 'imgs/header_background.png' %}')">
    <p class="m-0">
        <a href="{% url 'app:index' %}" class="text-orange hover-white">Home</a>
        >
        <a href="#" class="text-white hover-white">Listing</a>
    </p>
    <h3>Our Listings</h3>
</div>

{% for i in apartments %}
    <div class="row mx-0 my-5 d-flex justify-content-center">
        <div class="listing_card col-xl-10 p-0">
            <div class="row m-0 d-flex justify-content-center">
                <div class="col-xl-3 listing_card_img p-0" style="background-image: url('{{ i.img.url }}')">
                    <!-- Start: price tag -->
                    <button class="btn btn-orange listing_price_tag">
                        <div class="text-white col-xl-12 p-0 fw-700 info_row">
                            $ {{ i.price }}
                            <span class="fw-500">/month</span>
                        </div>
                    </button>
                    <!-- End: price tag -->
                </div>
                <div class="col-xl-9 px-4 py-3">
                    <h3>{{ i.name }}</h3>
                    <div class="row m-0 p-0 fw-400 text-black">
                        <img src="{% static 'icons/location_black.png' %}" class="mr-2 mt-1" style="height: 20px;">
                        <p class="mt-1 fs-15">{{ i.location }}</p>
                    </div>
                    <!-- Need to add ... for long description -->
                    <div class="fs-14 cut-text">
                        {{ i.about }}
                    </div>
                    <h6 class="fw-600 mt-3">
                        Facilities-
                    </h6>
                    <!-- start: all facilities -->
                    <div class="row m-0">
                        {% if i.garage %}
                        <div class="col-xl-4 p-0">
                            <div class="row m-0">
                                <i class="fa fa-check-square mt-1 mr-2"></i>
                                Avaiavle Garage
                            </div>
                        </div>
                        {% endif %}
                        {% if i.watchman %}
                        <div class="col-xl-4 p-0">
                            <div class="row m-0">
                                <i class="fa fa-check-square mt-1 mr-2"></i>
                                Full Time Security
                            </div>
                        </div>
                        {% endif %}
                        {% if i.garden %}
                        <div class="col-xl-4 p-0">
                            <div class="row m-0">
                                <i class="fa fa-check-square mt-1 mr-2"></i>
                                Attatched Garden
                            </div>
                        </div>
                        {% endif %}
                        {% if i.swimmingpool %}
                        <div class="col-xl-4 p-0">
                            <div class="row m-0">
                                <i class="fa fa-check-square mt-1 mr-2"></i>
                                Swimming Pool
                            </div>
                        </div>
                        {% endif %}
                        {% if i.hospital %}
                        <div class="col-xl-4 p-0">
                            <div class="row m-0">
                                <i class="fa fa-check-square mt-1 mr-2"></i>
                                Nearby Hospital
                            </div>
                        </div>
                        {% endif %}
                        {% if i.shoppingmall %}
                        <div class="col-xl-4 p-0">
                            <div class="row m-0">
                                <i class="fa fa-check-square mt-1 mr-2"></i>
                                Nearby Shopping mall
                            </div>
                        </div>
                        {% endif %}
                    </div>
                    <!-- end: all facilities -->
                    <!-- start: room numbers -->
                    <div class="row mx-0 mt-4">
                        <div class="col-xl-3 p-0">
                            <div class="row m-0">
                                <img src="{% static 'icons/bedroom.png' %}" style="height: 16px;" class="mr-3 mt-1">
                                <p>{{ i.bedroom }} Bedroom</p>
                            </div>
                        </div>
                        <div class="col-xl-3 p-0">
                            <div class="row m-0">
                                <img src="{% static 'icons/living.png' %}" style="height: 20px;" class="mr-3">
                                <p>{{ i.living }} Living</p>
                            </div>
                        </div>
                        <div class="col-xl-3 p-0">
                            <div class="row m-0">
                                <img src="{% static 'icons/dinning.png' %}" style="height: 18px;" class="mr-3 mt-1">
                                <p>{{ i.dinning }} Dinning</p>
                            </div>
                        </div>
                        <div class="col-xl-3 p-0">
                            <div class="row m-0">
                                <img src="{% static 'icons/bathroom.png' %}" style="height: 18px;" class="mr-3">
                                <p>{{ i.bathroom }} Bathroom</p>
                            </div>
                        </div>
                    </div>
                    <!-- end: room numbers -->
                    <a href="{% url 'app:apartment' pk=i.pk %}" class="btn btn-outline-dark text-black fw-400 px-4">GO TO DETAILS</a>
                </div>
            </div>
        </div>
    </div>
{% endfor %}


<div style="height: 60px;"></div>


{% endblock %}

FullStack/app/templates/app/notification.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid m-0 page_header p-5" style="background-image: url('{% static 'imgs/header_background.png' %}')">
    <p class="m-0">
        <a href="{% url 'app:index' %}" class="text-orange hover-white">Home</a>
        >
        <a href="#" class="text-white hover-white">Agent</a>
    </p>
    <h3>Notification Panel</h3>
</div>

<div class="row mx-0 my-5 d-flex justify-content-center">
    <div class="col-xl-10">
        {% if notification %}
            <table class="table table-striped table-hover" id ="sort">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Apartment</th>
                        <th scope="col">Topic</th>
                        <th scope="col">Message</th>
                        <th scope="col">Recieving Time</th>
                        {% if this_user.is_agent %}
                            <th scope="col">Action</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for i in notification %}
                        <tr>
                            <th scope="row">{{ i.pk }}</th>
                            <td>{{ i.apartment }}</td>
                            <td>{{ i.topic }}</td>
                            <td>{{ i.message }}</td>
                            <td>{{ i.recieve_time }}</td>
                            {% if this_user.is_agent and this_user.is_varified %}
                                <td>
                                    {% if i.is_approved %}
                                        <p class="text-info">Approved</button>
                                    {% else %}
                                    <form method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="noti_pk" value="{{ i.pk }}">
                                        <input type="hidden" name="apartment_pk" value="{{ i.apartment.pk }}">
                                        <button type="submit" class="btn btn-sm btn-success">Confirm</button>
                                    </form>
                                    {% endif %}
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <img src="{% static 'imgs/not_found.svg' %}" class="img-fluid d-flex mx-auto" style="height: 300px;">
        {% endif %}
    </div>
</div>


<div style="height: 240px;"></div>


{% endblock %}

FullStack/app/templates/app/profile.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="bg-lightgrey">
    <div class="row m-0 py-5 px-2 d-flex justify-content-center">
        <div class="col-xl-4 col-md-6 mx-2 profile_pic" style="background-image: url('{{ this_user.img.url }}')">
            <div class="profile_tag">
                <div class="row m-0">
                    <img src="{% static 'icons/profile_active_ico.png' %}" class="mt-1 mr-3">
                    {% if this_user.is_customer %}
                        Customer
                    {% elif this_user.is_agent %}
                        Agent
                    {% endif %}
                </div>                
            </div>
        </div>
        <div class="col-xl-5 mx-2 profile_description font_Commissioner">
            <h3 class="fw-800">{{ this_user.fullname }}</h3>
            <div class="row m-0">
                <p>{{ this_user.job }}</p>
                {% if own_page %}
                <a href="#" class="ml-auto hover_scale-9" data-toggle="modal" data-target="#deleteconformationmodal">
                    <img src="{% static 'icons/trash.png' %}" class="mr-2" style="height: 20px;">
                </a>
                <a href="#" class="ml-2 hover_scale-9" style="margin-top: 2px;">
                    <i class="fa fa-pencil text-grey fs-22"></i>
                </a>
                {% endif %}
            </div>
            <div class="profile_points my-4 py-3">
                <div class="row m-0 pt-2">
                    <p class="fw-800 font_Josefin text-upper">JOINED:</p>
                    <p class="fw-400 ml-auto fs-14">{{ this_user.joined }}</p>
                </div>
                <div class="row m-0">
                    <p class="fw-800 font_Josefin text-upper">Age:</p>
                    <p class="fw-400 ml-auto fs-14">{{ this_user.age }} Years</p>
                </div>
                <div class="row m-0">
                    <p class="fw-800 font_Josefin text-upper">Phone No:</p>
                    <p class="fw-400 ml-auto fs-14">{{ this_user.phone }}</p>
                </div>
                <div class="row m-0">
                    <p class="fw-800 font_Josefin text-upper">EMAIL:</p>
                    <p class="fw-400 ml-auto fs-14">{{ this_user.email }}</p>
                </div>
            </div>
            <div class="row m-0">
                <a href="{{ this_user.fb_link }}" class="profile_social mx-2">
                    <img src="{% static 'icons/facebook.png' %}">
                </a>
                <a href="{{ this_user.twitter_link }}" class="profile_social mx-2">
                    <img src="{% static 'icons/twitter.png' %}">
                </a>
                <a href="{{ this_user.linkedin_link }}" class="profile_social mx-2">
                    <img src="{% static 'icons/linkedin.png' %}">
                </a>
                <a href="{{ this_user.website_link }}" class="profile_social mx-2">
                    <img src="{% static 'icons/info.png' %}">
                </a>
            </div>
        </div>
    </div>

    <div class="container-fluid my-5">
        <div class="row m-0 prx-4 d-flex justify-content-center">
            <div class="col-xl-10 prx-45">
                <h4 class="fw-800 my-3">About {{ this_user.fullname }}</h4>
                <p class="profile_about">
                    {{ this_user.about }}
                </p>
            </div>
        </div>
    </div>


    <div class="container-fluid my-5">
        <div class="row m-0 prx-4 d-flex justify-content-center">
            <div class="col-xl-10 prx-45">
                <div class="row m-0">
                    <div class="col-xl-8 p-0">
                        <h4 class="fw-800 my-3">All Attatched Listing</h4>
                    </div>
                    {% if allow_add %}
                        <div class="col-xl-4 p-0">
                            <a href="{% url 'app:add_apartment' %}" class="btn btn-sm btn-orange float-right mt-3 px-3">
                                <i class="fa fa-plus mx-1"></i>
                                Add Items
                            </a>
                        </div>
                    {% endif %}
                </div>
                <!-- Start: attatched Listing -->
                {% if listing %}
                    <div class="row m-0 d-flex justify-content-center">
                        {% for i in listing %}
                        <!-- start: Dream_Card-->
                        <a href="{% url 'app:apartment' pk=i.pk %}">
                            <div class="dream_card mx-4">
                                <div class="dream_card_img" style="background-image: url('{{ i.img.url }}');">
                                    <div class="non_hover_content">
                                        <div class="tl_tag bg-orange d-flex justify-content-center">
                                            {{ i.name }}
                                        </div>
                                        <div class="row m-0 card_info py-3">
                                            <div class="text-orange col-xl-12 p-0 fw-700 info_row">
                                                $ {{ i.price }}
                                                <span class="fw-500">/month</span>
                                            </div>
                                            <div class="fw-200 text-white col-xl-12 p-0">
                                                <img src="{% static 'icons/Icon material-location-on.png' %}" class="mr-1">
                                                {{ i.location }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="overlay_content">
                                        <p>{{ i.name }}</p>
                                        <p class="fw-800">$ {{ i.price }}</p>
                                        <button class="btn btn-orange my-1 px-4">view details</button>
                                        <img class="d-flex my-2" src="{% static 'icons/card_ico.png' %}" style="width: 30px; height: 30px;">
                                        <p class="">{{ i.location }}</p>
                                </div>
                            </div>
                        </a>
                        <!-- End: Dream_Card-->
                        {% endfor %}
                    </div>
                {% else %}
                    <img src="{% static 'imgs/not_found.svg' %}" class="img-fluid d-flex mx-auto" style="height: 300px;">
                {% endif %}
                <!-- End: attatched Listing -->
            </div>
        </div>
    </div>

    <div style="height: 120px;"></div>

</div>


<!-- Start: Delet Confirm Modal -->
<div class="modal fade" id="deleteconformationmodal" tabindex="-1" role="dialog" aria-labelledby="deleteconformationmodalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteconformationmodalLabel">Delete Profile</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'app:delete_profile' pk=this_user.pk %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    Are you sure about delete your profile?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Process Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End: Delet Confirm Modal -->

{% endblock %}