FullStack/Dream_Housing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FullStack/app/urls.py
from django.urls import path
from app.views import *

app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('login_view/', login_view, name='login_view'),
    path('log_out_view/', log_out_view, name='log_out_view'),
    path('registration/', registration, name='registration'),
    path('profile/<str:pk>', profile, name='profile'),
    path('delete_profile/<str:pk>', delete_profile, name='delete_profile'),
    path('notification', notification, name='notification'),
    
    path('listing/', listing, name='listing'),
    path('rent_listing/', rent_listing, name='rent_listing'),
    path('sale_listing/', sale_listing, name='sale_listing'),
    path('search_result/', search_result, name='search_result'),
    
    path('apartment/<int:pk>', apartment, name='apartment'),
    path('add_apartment/', add_apartment, name='add_apartment'),
    path('edit_apartment/<int:pk>', edit_apartment, name='edit_apartment'),
    path('delete_apartment/', delete_apartment, name='delete_apartment'),
    path('agents/', agents, name='agents'),
    
    path('pay_a_visit/', pay_a_visit, name='pay_a_visit'),
    path('booking/', booking, name='booking'),

]

FullStack/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>

    <title>Dream Lodging</title>
	<link rel="icon" type="image/x-icon" href="{% static 'icons/logo.png' %}">

    <meta charset="UTF-8">

  	<!-- media queary support -->
  	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />

  	<!-- Latest compiled and minified CSS -->
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

  	<!-- jQuery library -->
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  	<!-- Popper JS -->
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

  	<!-- Latest compiled JavaScript -->
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

  	<!-- animated css link -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>

	<!-- Link Swiper's CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css"/>

  	<!-- font awsome css link -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  	<!-- poppins font link -->
  	<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>

  	<!-- google font link -->
  	<link href='https://fonts.googleapis.com/css?family=Open Sans:100,200,300,400,500,600,700,800,900|Ubuntu:100,200,300,400,500,600,700,800,900' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900|Ubuntu:100,200,300,400,500,600,700,800,900' rel='stylesheet'>
	<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Roboto+Serif:ital,opsz,wght@0,8..144,100;0,8..144,200;0,8..144,300;0,8..144,400;0,8..144,500;0,8..144,600;0,8..144,700;0,8..144,800;0,8..144,900;1,8..144,100;1,8..144,200;1,8..144,300;1,8..144,400;1,8..144,500;1,8..144,600;1,8..144,700;1,8..144,800;1,8..144,900&display=swap" rel="stylesheet">

  	<!-- custom css link -->
  	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	

  </head>
  <body>
    
    <div class="row m-0 top_nav" id="topnav">
		<div class="row m-0 ml-auto mr-5 pt-2 top_nav_ico_grp">
			<img src="{% static 'icons/ico_phone.png' %}" alt="" class="mt-1 mr-3 top_nav_ico">
			<p class="top_nav_text">+88 01752 452189</p>
		</div>
		<div class="row m-0 mx-5 pt-2 top_nav_ico_grp">
			<img src="{% static 'icons/ico_location.png' %}" alt="" class="mt-1 mr-3 top_nav_ico">
			<p class="top_nav_text">1/b/2 Adabor, Dhaka</p>
		</div>
    </div>

	<nav class="navbar navbar-expand-lg navbar-light bg-white sticky-top dream_nav px-4">
		<a class="navbar-brand" href="{% url 'app:index' %}">
			<img src="{% static 'icons/logo.png' %}" class="ml-3 navbar_logo">
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav m-auto">
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'app:index' %}">Home <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'app:index' %}#about">About Us</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Listing
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'app:rent_listing' %}">Rent</a>
						<a class="dropdown-item" href="{% url 'app:sale_listing' %}">Sale</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'app:listing' %}">All</a>
					</div>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'app:agents' %}">Agents</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#contact">Contact Us</a>
				</li>
			</ul>
			<ul class="navbar-nav mr-3">
				{% if user.is_authenticated %}
					<div class="row m-0">
						<a href="{% url 'app:index' %}#topnav" class="my-2 px-3">
							<img src="{% static 'icons/nav_src.png' %}" class="nav_lgin_ico">
						</a>
						<a href="{% url 'app:profile' pk=user %}" class="my-2 px-3 nav_ico_brdr">
							<img src="{% static 'icons/nav_user.png' %}" class="nav_lgin_ico">
						</a>
						<a href="{% url 'app:notification' %}" class="my-2 px-3 nav_ico_brdr">
							<img src="{% static 'icons/nav_bell.png' %}" class="nav_lgin_ico">
						</a>
						<a href="{% url 'app:log_out_view' %}" class="my-2 px-3">
							<img src="{% static 'icons/nav_logout.png' %}" class="nav_lgin_ico">
						</a>
					</div>
				{% else %}
					<a href="{% url 'app:index' %}#topnav" class="btn btn-outline-dark my-2 px-4 my-sm-0 mx-1">
						<i class="fa fa-search pr-1"></i>
						Search
					</a>
					<button class="btn btn-orange my-2 px-4 my-sm-0 mx-1" data-toggle="modal" data-target="#loginModal">
						<i class="fa fa-address-book pr-1"></i>
						Login
					</button>
				{% endif %}
			</ul>
		</div>
	</nav>

	<!-- Start: Login Modal -->
	<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content login_modal p-0">
				<div class="modal-header ml-auto mr-2" style="border: none;">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body m-0" style="width: 85% !important;">
					<img src="{% static 'icons/logo.png' %}" class="img-fluid d-flex mx-auto pb-2">
					<h5 class="fw-400 text-center pt-4 m-0">Welcome to Dream Lodging!</h5>
					<p class="fw-300 text-center m-1 p-0">Please fill up the form to login</p>
					<form action="{% url 'app:login_view' %}" method="POST" class="my-5">
						{% csrf_token %}
						<div class="form-group">
							<input type="text" class="form-control" name="username" placeholder="Enter Username">
						</div>
						<div class="form-group">
							<input type="password" class="form-control" name="password" placeholder="Enter Password">
						</div>
						<a href="{% url 'app:registration' %}" class="fw-500 cursor_hand">
							Don't have an account? 
							<span class="text-orange">Register</span>
						</a>
						<div class="row m-0 mt-5 d-flex justify-content-center">
							<button type="button" class="btn btn-dark mx-1 px-4" data-dismiss="modal">Close</button>
							<button type="submit" class="btn btn-orange mx-1">Submit</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- End: Login Modal -->

	


    {% block content %}
    
    {% endblock %}



	<div class="row m-0 dream_footer d-flex justify-content-center" id="contact">
		<div class="col-xl-3 col-md-6 col-sm-8" style="min-height: 300px;">
			<h3>Contact Us</h3>
			<ul class="footer_list my-4 px-2">
				<li>
					<img src="{% static 'icons/Icon ionic-md-call.png' %}" class="mr-3">
					+88 01741624086
				</li>
				<li>
					<img src="{% static 'icons/Icon ionic-ios-mail.png' %}" class="mr-3">
					dreamlodging.123@gmail.com
				</li>
				<li>
					<img src="{% static 'icons/Icon material-location-on.png' %}" class="mr-4">
					1/b/2 Adabor, Dhaka
				</li>
			</ul>
			<button class="btn btn-light mt-2 px-3">
				<i class='fa fa-location-arrow mr-2'></i>
				Find us on google map
			</button>
		</div>
		<div class="col-xl-4 footer_spacer" style="height: 250px;"></div>
		<div class="col-xl-3 col-md-6 col-sm-8" style="min-height: 250px;">
			<h4 class="text-right">We Offer</h4>
			<ul class="footer_list my-3 px-2 float-right text-right">
				<li>
					Buying an apartment
					<img src="{% static 'icons/Iconly-Light-Outline-Arrow---Left-3.png' %}" class="ml-2">
				</li>
				<li>
					Selling an apartment
					<img src="{% static 'icons/Iconly-Light-Outline-Arrow---Left-3.png' %}" class="ml-2">
				</li>
				<li>
					Renting an apartment
					<img src="{% static 'icons/Iconly-Light-Outline-Arrow---Left-3.png' %}" class="ml-2">
				</li>
			</ul>
			<div style="clear: both;"></div>

			<ul class="footer_menu float-right text-right mt-3">
				<li class="footer_active">Home</li>
				<li class="br-w1 ml-1 mr-2"></li>
				<li>About Us</li>
				<li class="br-w1  ml-1 mr-2"></li>
				<li>Listings</li>
				<li class="br-w1  ml-1 mr-2"></li>
				<li>Agents</li>
				<li class="br-w1  ml-1 mr-2"></li>
				<li>Review</li>
				<li class="br-w1  ml-1 mr-2"></li>
				<li>Contact Us</li>				
			</ul>
			<div style="clear: both;"></div>

		</div>
	</div>

	<div class="row m-0 d-flex justify,content-center bg-light">
		<p class="pt-3 mx-auto">Copyright reserved by Dream Lodging</p>
	</div>

  </body>
</html>



<!-- Table Sorting Library -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
<script src=" https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>

<script>
$(document).ready(function() {
    $('#sort').DataTable();
} );
</script>




<!-- Swiper JS -->
<script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>

<!-- Initialize Swiper -->
<script>
	var swiper = new Swiper("#swiper1", {
		slidesPerView: 1,
		centeredSlides: false,
		slidesPerGroupSkip: 1,
		grabCursor: true,
		keyboard: {
			enabled: true,
		},
		breakpoints: {
			769: {
			slidesPerView: 3,
			slidesPerGroup: 3,
			},
		},
		scrollbar: {
			el: ".swiper-scrollbar",
		},
		navigation: {
			nextEl: ".slider_next",
			prevEl: ".slider_prev",
		},
		pagination: {
			el: ".swiper-pagination",
			clickable: true,
		},
	});
	var swiper = new Swiper("#swiper2", {
		slidesPerView: 1,
		centeredSlides: false,
		slidesPerGroupSkip: 1,
		grabCursor: true,
		keyboard: {
			enabled: true,
		},
		breakpoints: {
			769: {
			slidesPerView: 3,
			slidesPerGroup: 3,
			},
		},
		scrollbar: {
			el: ".swiper-scrollbar",
		},
		navigation: {
			nextEl: ".slider_next",
			prevEl: ".slider_prev",
		},
		pagination: {
			el: ".swiper-pagination",
			clickable: true,
		},
	});
</script>